### ISSUE TITLE
unusual traffic from your computer network

### ISSUE THREAD

**Issue by biolee** [racaljk/hosts#1026]
About this page

Our systems have detected unusual traffic from your computer network. This page checks to see if it's really you sending the requests, and not a robot. Why did this happen?

**Comment by lrinQVQ** [comment]
google search?

**Comment by DDoSolitary** [comment]
`not is` => `is not`?
强迫症又发了。。

**Comment by EMLVIRUS** [comment]
其实 @DDoSolitary 说的没毛病

**Comment by lrinQVQ** [comment]
2333强迫症

**Comment by myguybetter** [comment]
The ip used in this file is a GGC one, and it usually hosted by local ISP. Because this file has been used by many people (mostly in CN), there would be large amounts of unrecognized traffic to this ip. So Google may think users like you as robots, not real human.

**Comment by derekwei** [comment]
这个提示真的很烦很烦，而且最近出现的频率越来越高了

**Comment by chonghua** [comment]
确实现在的频率有点高，不过也没办法吧

**Comment by dddcharlie** [comment]
Then how come the IP they detect unusual traffic is actually my own IP address and not the IP address in the hosts file (61.***).  Does everyone else face this issue as well?

**Comment by charlesdong** [comment]
+1. I have this problem when accessing Google too. That's why I gave up hosts and used Lantern to go across the GFW. But Lantern slows down the connection to Chinese sites (e.g. Baidu) even though I closed and even uninstalled it, and it's said that [Lantern causes ads](http://bbs.feng.com/read-htm-tid-11002470.html). So I still have to use hosts now.

**Comment by lrinQVQ** [comment]
fix now

**Comment by biolee** [comment]
@lrinQVQ i update the latest hosts, the problem remains

**Comment by lrinQVQ** [comment]
0.0
