### ISSUE TITLE
这个博客作者可以的233贼6

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1146]
![2017-05-22 20-01-18](https://cloud.githubusercontent.com/assets/12861134/26307968/cc6b7024-3f29-11e7-8d89-5d6dfc45f2c8.png)

**Comment by EMLVIRUS** [comment]
学习一下FFmpeg建立一个名录？（写在wiki或单独一个.md）？

**Comment by lrinQVQ** [comment]
好啊~

**Comment by lrinQVQ** [comment]
按照他的意思就是0.0 在国内没有版权喽0.0

**Comment by EMLVIRUS** [comment]
┑(￣Д ￣)┍ばかの治療法ではありません

**Comment by DennisWong** [comment]
这种脑残也是没救了(*´◐∀◐`*)智障来自我的华为手机-------- 原始邮件 --------主题：Re: [racaljk/hosts] 这个博客作者可以的233贼6 (#1146)发件人：EMLVIRUS 收件人：racaljk/hosts 抄送：Subscribed ┑(￣Д ￣)┍ばかの治療法ではありません

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/racaljk/hosts","title":"racaljk/hosts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/racaljk/hosts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EMLVIRUS in #1146: ┑(￣Д ￣)┍ばかの治療法ではありません"}],"action":{"name":"View Issue","url":"https://github.com/racaljk/hosts/issues/1146#issuecomment-303086308"}}}

**Comment by dawangjiaowolaifatie** [comment]
这种人没有是非观念的。抄袭别人东西就是不对，还需要问有没有版权吗？还需要查法律手册吗？他的意思是要是法律没规定杀人偿命他就可以上街随便杀人了。

对待这种人要么就是不理，要么就是以其人之道还治其人之身，以恶制恶，以战止战。别无他法。

**Comment by lrinQVQ** [comment]
同意楼上233

**Comment by lrinQVQ** [comment]
http://www.shaoit.com/googlehosts.html/comment-page-2#comments
嘛～借用@dawangjiaowolaifatie 的话我怼去了233

**Comment by DDoSolitary** [comment]
@lrinQVQ 我没看到诶，被删评论了吗

**Comment by aofall** [comment]
这人的不要脸是出了名的，以前打包别人修改的软件就被婊了很久。

类似的站点有很多，这些站点往往厉害的地方就是做SEO，大量的采集各种资源。

license在国内真的没有什么好的约束能力，只能靠自觉和舆论监督了

**Comment by lrinQVQ** [comment]
@DDoSolitary 被删了２３３

**Comment by lrinQVQ** [comment]
@aofall 确实233

**Comment by lychichem** [comment]
恕我直言，对国内来说，license就是个xx，你看连国家都在抄

**Comment by EMLVIRUS** [comment]
> license 就是个 xx，你看连国家都在抄

我竟然找不出一丝毛病

**Comment by peterzane** [comment]
这人前几年我还经常用他搜集的软件了，把一些必须在论坛博客上才能找的资源集合起来挂上一个“来自网络”就放自己网站上供别人下载，跟老D一样搜索引擎排名巨靠前，特别是用百度的时候，后来他的很多资源必须关注微信才给发就没用了。不过他的网站对小白来说确实很受用，全中文，无需番羽土墙，赚点流量也是应该的，我室友javaweb学的比我⑥但是他从来不上github，获取成本的问题而已，我的路由器把baidu.com变成了405 not allowed他还让我换路由器。

**Comment by Too-Naive** [comment]
@peterzane 哈哈哈哈最後的 405 好評！

**Comment by laodcn** [comment]
@peterzane 为什么每次都是我中枪？

**Comment by lrinQVQ** [comment]
@laodcn 因为你太有名2333

**Comment by lrinQVQ** [comment]
@peterzane 405好评2333

**Comment by lrinQVQ** [comment]
![2017-05-24 18-39-15](https://cloud.githubusercontent.com/assets/12861134/26399673/589f453e-40b0-11e7-9fab-3c6a678ffa18.png)
他还是耸了233
