### ISSUE TITLE
Invalid script url address

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#398]
@K-Guan Something wrong at /tools/README.md "script file url"(return 404)
Can you help us solve this problem?

**Comment by K-Guan** [comment]
I think I could, yes. But I'm kinda busy now, will solve that in 2 hours.

**Comment by Too-Naive** [comment]
OK

**Comment by K-Guan** [comment]
Got it. The problem is because:

![screenshot from 2016-04-22 21-54-28](https://cloud.githubusercontent.com/assets/13862535/14743760/cd392e82-08d5-11e6-9a57-b4cda607444e.png)

So when you changed the path to scripts, my code doesn't work.

Here's the output of `diff` command:

![screenshot from 2016-04-22 22-11-48](https://cloud.githubusercontent.com/assets/13862535/14744319/e2b2e41c-08d8-11e6-8f92-fef81462ab38.png)

And, I've already fixed the issue.

**Comment by Too-Naive** [comment]
Thx a lot.(BTW: y not save the script to server?

**Comment by K-Guan** [comment]
@Too-Naive Well, I *thought* I did. But maybe I didn't because that then I have to re-save the scripts if you guys updated the scripts on GitHub, so meh.

**Comment by Too-Naive** [comment]
I think, too.

**Comment by Too-Naive** [comment]
New Pull Request will also change the script name......(233

**Comment by K-Guan** [comment]
I see...doesn't mater...
