### ISSUE TITLE
Google域名经常需要使用验证码

### ISSUE THREAD

**Issue by pinguo-gaoshan** [racaljk/hosts#656]
访问类似这种网址
https://www.google.com/search?ie=utf-8&oe=utf-8&lr=lang_zh-CN&aq=t&q=sdfsdf

结果经常跳转到一个ipv4.google.com/xxxxxx 然后输入一个验证码之后才能使用

**Comment by viro** [comment]
https://support.google.com/websearch/answer/86640?hl=zh-Hans

**Comment by imknown** [comment]
~~是不是你家邻居在干坏事~~

**Comment by foobra** [comment]
有可能, 我们公司局域网内很多人都在使用这个hosts, 可能是单ip访问量太大?

**Comment by huahuayu** [comment]
我之前一直用都没有，最近一周内常出现同样情况，即要输入验证码。谷歌提示说监测到流量有异常。Sent from iPhone
--------------------------------------  
Thanks & regards
Shiming Liu, PMP  
Tel: +(86) 18520319552
E-mail: codingmylife@gmail.com
            在2016年09月26日 12:18，pinguo_gaoshan 写道:有可能, 我们公司局域网内很多人都在使用这个hosts, 可能是单ip访问量太大?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/racaljk/hosts","title":"racaljk/hosts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/racaljk/hosts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@foobra in #656: 有可能, 我们公司局域网内很多人都在使用这个hosts, 可能是单ip访问量太大?"}],"action":{"name":"View Issue","url":"https://github.com/racaljk/hosts/issues/656#issuecomment-249476269"}}}

**Comment by lautis0503** [comment]
之前也出现过几次，最近几天比较频繁

**Comment by CNHBH** [comment]
#  **使用 Tor 网络也会遇到这种情况！**

**Comment by scalpelx** [comment]
这段时间经常遇到，在家里，非局域网，附近应该也没有会用Google的。

**Comment by imknown** [comment]
确实 我这几天在家用Windows 偶尔会碰到, 
Ubuntu ~~运气差~~ 没有一直没遇到. 
在公司 反而 并没有.

**Comment by imknown** [comment]
我把谷歌原话拷贝下来了:

***

**关于此网页**

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认
这些请求是由您而不是自动程序发出的。[为什么会这样？][#]

> 如果 Google 自动检测到从您的计算机网络发出的请求可能违反
[服务条款][服务条款]，就会显示此网页。这些请求一旦停止，此阻断即会失
效。在此期间，如果您能破解上述人机识别系统，就可以继续使
用我们的服务。

> 该流量可能是由恶意软件、浏览器插件或发送自动请求的脚本发
出的。如果您与他人共享网络连接，请向管理员寻求帮助 — 这可
能是由多台计算机使用同一 IP 地址导致的。[了解详情][了解详情]

> 有时，如果您使用的是自动程序普遍使用的高级条款或者正在快
速连续地发送请求，则可能需要破解人机识别系统。

[#]: http://  
[服务条款]: https://www.google.com/policies/terms/  
[了解详情]: https://support.google.com/websearch/answer/86640

**Comment by hzj629206** [comment]
我最近也遇到了。最近才出现的。

**Comment by WeihuaGu** [comment]
android 手机中的google也出现了。今天还出现了一次登录手机版twitter，要从邮箱中接受验证码，才能登录不知道有没有关联。

**Comment by viro** [comment]
可能是这个 IP 用的人太多了吧，在那个关于火狐浏览器的 issue 里面有 Google 官方 IP，
上次也有 issue 提到过 202 开头的 IP，我建议可以更换 Google IP。

本项目中的 hosts 被不少手机论坛传播，很多改 Android ROM 的开发者把 ROM 里
hosts 替换成这里的 hosts，用的人应该比想象中还多。

**Comment by imcaffrey** [comment]
唔 说到可用的ip history里面就有好多（

**Comment by andytimes** [comment]
@imcaffrey Google 好像隔一段时间就会新增 IP 段，但不知道现在封得厉不厉害了。
不知道为什么 220.x.x.x 能存活这么久，最近 XX-Net 那边也经常反馈验证码的事情，
看来不是个例，不知道是什么情况：

https://github.com/XX-net/XX-Net/issues?utf8=%E2%9C%93&q=is%3Aissue%20%E9%AA%8C%E8%AF%81%E7%A0%81

**Comment by imcaffrey** [comment]
好谜啊。。。 https://github.com/XX-net/XX-Net/issues/4128#issuecomment-243188504

**Comment by andytimes** [comment]
@imcaffrey 我不是很了解 GoAgent，XX-Net 之类的，但我猜它们默认模式都是走 appspot 的流量，
那个规则写着 hosts，可能就类似 hosts 那样，把 Google 相关网站用 IP 访问。

220.255.2.153 这个 IP 是支持 Appspot 的。

**Comment by imcaffrey** [comment]
不是很懂。。。你看comment里面说改成direct是和hosts一个效果的。。。好谜啊

**Comment by KalelCooper** [comment]
I have same issue with 64.233.162.81
