### ISSUE TITLE
今早起来fb打不开

### ISSUE THREAD

**Issue by whzecomjm** [racaljk/hosts#688]
今早起来fb打不开，更新hosts以后问题依然存在。

**Comment by myguybetter** [comment]
Same. That ip was blocked.

**Comment by gundamgogogo** [comment]
same here

**Comment by xuewuhen0202** [comment]
same here.

**Comment by Too-Naive** [comment]
请说一下你们的地区 谢谢



On xuewuhen0202 <notifications@github.com>, Oct 11, 2016 10:15 AM wrote:

same here.

**Comment by sqc1999** [comment]
浙江绍兴，我这里也打不开。

**Comment by xuewuhen0202** [comment]
@Too-Naive 上海浦东

**Comment by myguybetter** [comment]
@Too-Naive The commit used a 3rd-party sniproxy ip rather than FB's official to fix the connectivity issue. Is it really appropriate?

**Comment by Too-Naive** [comment]
FB use https to transmit data, we just trust it will secure. If I revert host that we still can't open FB website.



On myguybetter <notifications@github.com>, Oct 12, 2016 1:58 PM wrote:

@Too-Naive<https://github.com/Too-Naive> The commit used a 3rd-party sniproxy ip rather than FB's official to fix the connectivity issue. Is it really appropriate?

**Comment by myguybetter** [comment]
@Too-Naive Got it. Thanks for your answering.

**Comment by imcaffrey** [comment]
@racaljk @andytimes 想问一下 #689 #683 是怎么回事
决定引入反代了么 以及 31.13.72.54 之类根本 ping 不通

**Comment by Too-Naive** [comment]
(可以暂时考虑反代？)
